### PR TITLE
No exception when publishing to not existing channels

### PR DESCRIPTION
**Pull request by wrichert**
By default no exception is thrown. If an exception should be thrown (as it was the default earlier), the command line switch --fail-publish-non-existing-channels has to be used.

### CODE REVIEW

**Comment by daxreyes** [comment]
I think its better to ensure that when a new option/parameter is added, if not set, will maintain the original expected logic instead of the other way around. Why not set to --ignore-publish-non-existing-channels instead of  --fail-publish-non-existing-channels ?

**Comment by wrichert** [comment]
True story. I have changed the particular commit f136e8f7eb382c9b40e88ed9a61632360d79003e accordingly.

**Comment by daxreyes** [comment]
Saw your commit 4614334a4878d528f1c6697996d0ef5a968fe461 , not sure what would be the effect when -p is both used for "-p", "--port", and '-p', '--ignore-publish-non-existing-channels' . Will it be better to change -p, I can not think of a suggested one letter parameter, any suggestions/ideas ?

**Comment by wrichert** [comment]
I've changed it to -x: 818f19f149cc2f1fc0c2d58351b79191115c3a79

**Pull request merged**
